class EventTypes(object):
    RECEIVE_MESSAGE = 26
    NOTIFIED_ADD_FOLLOW = 84
    NOTIFIED_DELETE_FOLLOW = 86
    NOTIFIED_INVITE_INTO_GROUP = 13
    NOTIFIED_INVITE_INTO_ROOM = 22
    NOTIFIED_KICKOUT_FROM_GROUP = 14
    NOTIFIED_KICKOUT_FROM_ROOM = 14
    LEAVE_GROUP = 14
    LEAVE_ROOM = 14
    NOTIFIED_POSTBACK = 90
    NOTIFIED_BEACON_DETECTED = 81
    NOTIFIED_CHANNEL_SYNC = 53
    
    EventDict = {
        "message": "RECEIVE_MESSAGE",
        "follow": "NOTIFIED_ADD_FOLLOW",
        "unfollow": "NOTIFIED_DELETE_FOLLOW",
        "join": "NOTIFIED_INVITE_INTO_GROUP",
        "leave": "NOTIFIED_KICKOUT_FROM_GROUP",
        "postback": "NOTIFIED_POSTBACK",
        "beacon": "NOTIFIED_BEACON_DETECTED",
        "accountLink": "RECEIVE_MESSAGE",
    }

    _VALUES_TO_NAMES = {
        26: "RECEIVE_MESSAGE",
        84: "NOTIFIED_ADD_FOLLOW",
        86: "NOTIFIED_DELETE_FOLLOW",
        13: "NOTIFIED_INVITE_INTO_GROUP",
        22: "NOTIFIED_INVITE_INTO_ROOM",
        14: "NOTIFIED_KICKOUT_FROM_GROUP",
        90: "NOTIFIED_POSTBACK",
        81: "NOTIFIED_BEACON_DETECTED",
        53: "NOTIFIED_CHANNEL_SYNC",
    }

    _NAMES_TO_VALUES = {
        "RECEIVE_MESSAGE": 26,
        "NOTIFIED_ADD_FOLLOW": 84,
        "NOTIFIED_DELETE_FOLLOW": 86,
        "NOTIFIED_INVITE_INTO_GROUP": 13,
        "NOTIFIED_INVITE_INTO_ROOM": 22,
        "NOTIFIED_KICKOUT_FROM_GROUP": 14,
        "NOTIFIED_POSTBACK": 90,
        "NOTIFIED_BEACON_DETECTED": 81,
        "NOTIFIED_CHANNEL_SYNC": 53
    }
    
    def __init__(self):
        pass